export const animes = [
  {
    titulo: "Naruto",
    nota: 7.9,
    sinopse: "Naruto Uzumaki é um jovem ninja que busca reconhecimento e sonha em se tornar Hokage, o líder de sua vila.",
    ano: 2002,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
    popularidade: 5,
    curiosidade: "Naruto originalmente teria uma premissa muito diferente, onde ele teria cauda de raposa apenas."
  },
  {
    titulo: "Naruto Shippuden",
    nota: 8.2,
    sinopse: "Continuação de Naruto, com uma história mais madura e batalhas épicas enquanto Naruto tenta salvar seu amigo Sasuke.",
    ano: 2007,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "https://cdn.myanimelist.net/images/anime/5/17407.jpg",
    popularidade: 3,
    curiosidade: "Naruto originalmente teria uma premissa muito diferente, onde ele teria cauda de raposa apenas."
  },
  {
    titulo: "One Piece",
    nota: 8.8,
    sinopse: "Monkey D. Luffy e sua tripulação navegam pelos mares em busca do tesouro lendário One Piece.",
    ano: 1999,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
    popularidade: 1,
    curiosidade: "One Piece é o mangá mais vendido da história do Japão."
  },
  {
    titulo: "Dragon Ball Z",
    nota: 8.7,
    sinopse: "Goku e seus amigos defendem a Terra contra poderosos inimigos e desafios de tirar o fôlego.",
    ano: 1989,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "https://cdn.myanimelist.net/images/anime/6/22049.jpg",
    popularidade: 2,
    curiosidade: "Dragon Ball Z popularizou as batalhas longas e transformações em animes."
  },
  {
    titulo: "Dragon Ball Super",
    nota: 8.2,
    sinopse: "A continuação oficial de Dragon Ball Z com novas batalhas, novos deuses e torneios épicos.",
    ano: 2015,
    temporada: "Verão",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "https://cdn.myanimelist.net/images/anime/5/74745.jpg",
    popularidade: 10,
    curiosidade: "Dragon Ball Super trouxe novos níveis de poder e deuses no universo Dragon Ball."
  },
  {
    titulo: "Attack on Titan",
    nota: 9.0,
    sinopse: "A humanidade luta pela sobrevivência contra titãs gigantes em um mundo sombrio e cheio de segredos.",
    ano: 2013,
    temporada: "Primavera",
    genero: ["Ação", "Drama", "Fantasia"],
    capa: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    popularidade: 4,
    curiosidade: "A obra inspirou debates filosóficos sobre liberdade e sacrifício."
  },
  {
    titulo: "Death Note",
    nota: 8.6,
    sinopse: "Um estudante obtém um caderno com o poder de matar quem tiver o nome escrito nele e enfrenta um detetive genial.",
    ano: 2006,
    temporada: "Outono",
    genero: ["Mistério", "Sobrenatural", "Psicológico"],
    capa: "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
    popularidade: 6,
    curiosidade: "Death Note teve um impacto cultural global, inspirando várias adaptações."
  },
  {
    titulo: "Fullmetal Alchemist: Brotherhood",
    nota: 9.2,
    sinopse: "Dois irmãos alquimistas buscam a Pedra Filosofal para recuperar seus corpos perdidos após uma transmutação proibida.",
    ano: 2009,
    temporada: "Primavera",
    genero: ["Ação", "Aventura", "Drama"],
    capa: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
    popularidade: 7,
    curiosidade: "A história é uma adaptação fiel ao mangá original."
  },
  {
    titulo: "My Hero Academia",
    nota: 8.0,
    sinopse: "Num mundo onde a maioria tem superpoderes, um jovem sem poderes sonha em ser um herói.",
    ano: 2016,
    temporada: "Primavera",
    genero: ["Ação", "Superpoderes", "Shounen"],
    capa: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
    popularidade: 8,
    curiosidade: "My Hero Academia é um dos animes shounen mais populares da década."
  },
  {
    titulo: "Demon Slayer",
    nota: 8.8,
    sinopse: "Tanjiro luta para salvar sua irmã e destruir demônios que assolam o mundo.",
    ano: 2019,
    temporada: "Primavera",
    genero: ["Ação", "Sobrenatural", "Drama"],
    capa: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    popularidade: 9,
    curiosidade: "Demon Slayer quebrou recordes de bilheteria no Japão."
  },
  {
    titulo: "Sword Art Online",
    nota: 7.6,
    sinopse: "Jogadores ficam presos num MMORPG e precisam lutar para sobreviver e escapar do jogo.",
    ano: 2012,
    temporada: "Verão",
    genero: ["Ação", "Aventura", "Romance"],
    capa: "https://cdn.myanimelist.net/images/anime/11/39717.jpg",
    popularidade: 15,
    curiosidade: "Sword Art Online ajudou a popularizar animes de jogos virtuais."
  },
  {
    titulo: "Tokyo Ghoul",
    nota: 7.9,
    sinopse: "Um jovem se torna meio ghoul após um ataque, enfrentando uma nova vida cheia de perigos.",
    ano: 2014,
    temporada: "Outono",
    genero: ["Ação", "Sobrenatural", "Drama"],
    capa: "https://cdn.myanimelist.net/images/anime/5/64449.jpg",
    popularidade: 14,
    curiosidade: "Tokyo Ghoul explora temas de identidade e aceitação."
  },
  {
    titulo: "Hunter x Hunter (2011)",
    nota: 8.7,
    sinopse: "Gon Freecss busca seu pai e enfrenta desafios para se tornar um Hunter.",
    ano: 2011,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
    popularidade: 12,
    curiosidade: "O autor de Hunter x Hunter é conhecido por suas pausas longas."
  },
  {
    titulo: "Bleach",
    nota: 7.8,
    sinopse: "Ichigo Kurosaki ganha poderes de Soul Reaper e protege o mundo dos espíritos malignos.",
    ano: 2004,
    temporada: "Outono",
    genero: ["Ação", "Sobrenatural", "Shounen"],
    capa: "https://cdn.myanimelist.net/images/anime/3/40451.jpg",
    popularidade: 13,
    curiosidade: "Bleach teve um grande impacto na cultura pop dos anos 2000."
  },
  {
    titulo: "Fairy Tail",
    nota: 7.5,
    sinopse: "Lucy e Natsu vivem aventuras mágicas em uma guilda cheia de amigos e perigos.",
    ano: 2009,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "https://cdn.myanimelist.net/images/anime/5/69696.jpg",
    popularidade: 11,
    curiosidade: "Fairy Tail é conhecido por sua forte ênfase em amizade."
  },
  {
    titulo: "Steins;Gate",
    nota: 9.1,
    sinopse: "Um grupo de amigos descobre uma forma de enviar mensagens ao passado e altera o destino.",
    ano: 2011,
    temporada: "Primavera",
    genero: ["Sci-Fi", "Suspense", "Drama"],
    capa: "https://cdn.myanimelist.net/images/anime/5/73199.jpg",
    popularidade: 16,
    curiosidade: "Steins;Gate é considerado um dos melhores animes de viagem no tempo."
  },
  {
    titulo: "Tokyo Revengers",
    nota: 7.9,
    sinopse: "Um homem volta no tempo para salvar sua namorada e mudar o destino das gangues de Tóquio.",
    ano: 2021,
    temporada: "Primavera",
    genero: ["Ação", "Drama", "Supernatural"],
    capa: "https://cdn.myanimelist.net/images/anime/1924/116635.jpg",
    popularidade: 18,
    curiosidade: "Tokyo Revengers traz uma mistura de drama e ação com viagem no tempo."
  },
  {
    titulo: "Mob Psycho 100",
    nota: 8.5,
    sinopse: "Mob é um garoto com poderes psíquicos que tenta viver uma vida normal enquanto enfrenta perigos.",
    ano: 2016,
    temporada: "Outono",
    genero: ["Ação", "Comédia", "Sobrenatural"],
    capa: "https://cdn.myanimelist.net/images/anime/8/78745.jpg",
    popularidade: 20,
    curiosidade: "Mob Psycho 100 é conhecido pelo seu estilo de animação único."
  }
];
