export const animes = [
  {
    titulo: "Naruto",
    nota: 7.9,
    sinopse: "Naruto Uzumaki é um jovem ninja que busca reconhecimento e sonha em se tornar Hokage, o líder de sua vila.",
    ano: 2002,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "src/design/images/naruto-clássico.jpg",
    popularidade: 5,
    curiosidade: "Naruto originalmente teria uma premissa muito diferente, onde ele teria cauda de raposa apenas."
  },
  {
    titulo: "Naruto Shippuden",
    nota: 8.2,
    sinopse: "Continuação de Naruto, com uma história mais madura e batalhas épicas enquanto Naruto tenta salvar seu amigo Sasuke.",
    ano: 2007,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "src/design/images/naruto-shippuden.jpg",
    popularidade: 3,
    curiosidade: "A Akatsuki originalmente não era uma organização maligna foi criada para proteger a Vila da Chuva."
  },
  {
    titulo: "One Piece",
    nota: 8.8,
    sinopse: "Monkey D. Luffy e sua tripulação navegam pelos mares em busca do tesouro lendário One Piece.",
    ano: 1999,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "src/design/images/one-piece.jpg",
    popularidade: 1,
    curiosidade: "One Piece é o mangá mais vendido da história do Japão."
  },
  {
    titulo: "Dragon Ball Z",
    nota: 8.7,
    sinopse: "Goku e seus amigos defendem a Terra contra poderosos inimigos e desafios de tirar o fôlego.",
    ano: 1989,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "src/design/images/dragon-ball-z.png",
    popularidade: 2,
    curiosidade: "Dragon Ball Z popularizou as batalhas longas e transformações em animes."
  },
  {
    titulo: "Dragon Ball Super",
    nota: 8.2,
    sinopse: "A continuação oficial de Dragon Ball Z com novas batalhas, novos deuses e torneios épicos.",
    ano: 2015,
    temporada: "Verão",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "src/design/images/dragon-ball-super.jpg",
    popularidade: 10,
    curiosidade: "Dragon Ball Super trouxe novos níveis de poder e deuses no universo Dragon Ball."
  },
  {
    titulo: "Attack on Titan",
    nota: 9.0,
    sinopse: "A humanidade luta pela sobrevivência contra titãs gigantes em um mundo sombrio e cheio de segredos.",
    ano: 2013,
    temporada: "Primavera",
    genero: ["Ação", "Drama", "Fantasia"],
    capa: "src/design/images/attack-on-titan.jpg",
    popularidade: 4,
    curiosidade: "A obra inspirou debates filosóficos sobre liberdade e sacrifício."
  },
  {
    titulo: "Death Note",
    nota: 8.6,
    sinopse: "Um estudante obtém um caderno com o poder de matar quem tiver o nome escrito nele e enfrenta um detetive genial.",
    ano: 2006,
    temporada: "Outono",
    genero: ["Mistério", "Sobrenatural", "Psicológico"],
    capa: "src/design/images/death-note.jpg",
    popularidade: 6,
    curiosidade: "Death Note teve um impacto cultural global, inspirando várias adaptações."
  },
  {
    titulo: "Fullmetal Alchemist: Brotherhood",
    nota: 9.2,
    sinopse: "Dois irmãos alquimistas buscam a Pedra Filosofal para recuperar seus corpos perdidos após uma transmutação proibida.",
    ano: 2009,
    temporada: "Primavera",
    genero: ["Ação", "Aventura", "Drama"],
    capa: "src/design/images/fullmetal-alchemist.jpg",
    popularidade: 7,
    curiosidade: "A história é uma adaptação fiel ao mangá original."
  },
  {
    titulo: "My Hero Academia",
    nota: 8.0,
    sinopse: "Num mundo onde a maioria tem superpoderes, um jovem sem poderes sonha em ser um herói.",
    ano: 2016,
    temporada: "Primavera",
    genero: ["Ação", "Superpoderes", "Shounen"],
    capa: "src/design/images/my-hero-academia.jpg",
    popularidade: 8,
    curiosidade: "My Hero Academia é um dos animes shounen mais populares da década."
  },
  {
    titulo: "Demon Slayer",
    nota: 8.8,
    sinopse: "Tanjiro luta para salvar sua irmã e destruir demônios que assolam o mundo.",
    ano: 2019,
    temporada: "Primavera",
    genero: ["Ação", "Sobrenatural", "Drama"],
    capa: "src/design/images/demon-slayer.jpg",
    popularidade: 9,
    curiosidade: "Demon Slayer quebrou recordes de bilheteria no Japão."
  },
  {
    titulo: "Sword Art Online",
    nota: 7.6,
    sinopse: "Jogadores ficam presos num MMORPG e precisam lutar para sobreviver e escapar do jogo.",
    ano: 2012,
    temporada: "Verão",
    genero: ["Ação", "Aventura", "Romance"],
    capa: "src/design/images/sword-art-online.jpg",
    popularidade: 15,
    curiosidade: "Sword Art Online ajudou a popularizar animes de jogos virtuais."
  },
  {
    titulo: "Tokyo Ghoul",
    nota: 7.9,
    sinopse: "Um jovem se torna meio ghoul após um ataque, enfrentando uma nova vida cheia de perigos.",
    ano: 2014,
    temporada: "Outono",
    genero: ["Ação", "Sobrenatural", "Drama"],
    capa: "src/design/images/tokyo-ghoul.jpg",
    popularidade: 14,
    curiosidade: "Tokyo Ghoul explora temas de identidade e aceitação."
  },
  {
    titulo: "Hunter x Hunter (2011)",
    nota: 8.7,
    sinopse: "Gon Freecss busca seu pai e enfrenta desafios para se tornar um Hunter.",
    ano: 2011,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Shounen"],
    capa: "src/design/images/hunter-hunter.jpg",
    popularidade: 12,
    curiosidade: "O autor de Hunter x Hunter é conhecido por suas pausas longas."
  },
  {
    titulo: "Bleach",
    nota: 7.8,
    sinopse: "Ichigo Kurosaki ganha poderes de Soul Reaper e protege o mundo dos espíritos malignos.",
    ano: 2004,
    temporada: "Outono",
    genero: ["Ação", "Sobrenatural", "Shounen"],
    capa: "src/design/images/bleach.jpg",
    popularidade: 13,
    curiosidade: "Bleach teve um grande impacto na cultura pop dos anos 2000."
  },
  {
    titulo: "Fairy Tail",
    nota: 7.5,
    sinopse: "Lucy e Natsu vivem aventuras mágicas em uma guilda cheia de amigos e perigos.",
    ano: 2009,
    temporada: "Outono",
    genero: ["Ação", "Aventura", "Fantasia"],
    capa: "src/design/images/fairy-tail.jpg",
    popularidade: 11,
    curiosidade: "Fairy Tail é conhecido por sua forte ênfase em amizade."
  },
  {
    titulo: "Steins;Gate",
    nota: 9.1,
    sinopse: "Um grupo de amigos descobre uma forma de enviar mensagens ao passado e altera o destino.",
    ano: 2011,
    temporada: "Primavera",
    genero: ["Sci-Fi", "Suspense", "Drama"],
    capa: "src/design/images/steins-gate.jpg",
    popularidade: 16,
    curiosidade: "Steins;Gate é considerado um dos melhores animes de viagem no tempo."
  },
  {
    titulo: "Tokyo Revengers",
    nota: 7.9,
    sinopse: "Um homem volta no tempo para salvar sua namorada e mudar o destino das gangues de Tóquio.",
    ano: 2021,
    temporada: "Primavera",
    genero: ["Ação", "Drama", "Supernatural"],
    capa: "src/design/images/tokyo-revengers.jpg",
    popularidade: 18,
    curiosidade: "Tokyo Revengers traz uma mistura de drama e ação com viagem no tempo."
  },
  {
    titulo: "Mob Psycho 100",
    nota: 8.5,
    sinopse: "Mob é um garoto com poderes psíquicos que tenta viver uma vida normal enquanto enfrenta perigos.",
    ano: 2016,
    temporada: "Verão",
    genero: ["Ação", "Comédia", "Sobrenatural"],
    capa: "src/design/images/mob-pyscho-100.jpg",
    popularidade: 20,
    curiosidade: "Mob Psycho 100 é conhecido pelo seu estilo de animação único."
  },
    {
      titulo: "One Punch Man",
      nota: 8.6,
      sinopse: "Saitama é um herói que derrota qualquer inimigo com apenas um soco, mas isso o deixa entediado com sua vida de super-herói.",
      ano: 2015,
      temporada: "Outono",
      genero: ["Ação", "Comédia", "Paródia"],
      capa: "src/design/images/one-punch-man.jpg",
      popularidade: 92,
      curiosidade: "A origem do personagem é uma webcomic criada pelo autor ONE antes de virar anime."
    },
    {
      titulo: "Cowboy Bebop",
      nota: 8.9,
      sinopse: "Um grupo de caçadores de recompensas viaja pelo espaço em busca de criminosos.",
      ano: 1998,
      temporada: "Outono",
      genero: ["Ação", "Aventura", "Sci-Fi"],
      capa: "src/design/images/cowboy-bebop.jpg",
      popularidade: 85,
      curiosidade: "A trilha sonora jazz é um dos destaques da série."
    },
    {
      titulo: "Your Lie in April",
      nota: 8.8,
      sinopse: "Um prodígio do piano encontra uma violinista que muda sua vida para sempre.",
      ano: 2014,
      temporada: "Outono",
      genero: ["Drama", "Romance", 
      "Música"],
      capa: "src/design/images/your-lie-in-april.jpg",
      popularidade: 80,
      curiosidade: "É conhecido por suas belas cenas musicais e emoção intensa."
    },
    {
      titulo: "Re:Zero − Starting Life in Another World",
      nota: 8.3,
      sinopse: "Subaru é transportado para um mundo paralelo e descobre que pode voltar no tempo ao morrer.",
      ano: 2016,
      temporada: "Primavera",
      genero: ["Fantasia", "Drama", "Suspense"],
      capa: "src/design/images/re-zero-starting.jpg",
      popularidade: 88,
      curiosidade: "O anime é baseado numa série de light novels populares."
    },
    {
      titulo: "Violet Evergarden",
      nota: 8.5,
      sinopse: "Após a guerra, Violet tenta entender sentimentos humanos enquanto escreve cartas para os outros.",
      ano: 2018,
      temporada: "Inverno",
      genero: ["Drama", "Slice of Life", "Fantasia"],
      capa: "src/design/images/violet-evergarden.jpg",
      popularidade: 75,
      curiosidade: "A animação é conhecida pela sua qualidade visual e emocional.",
    },
    {
      titulo: "Made in Abyss",
      nota: 8.7,
      sinopse: "Riko desce nas profundezas do Abismo para encontrar sua mãe e descobrir segredos perigosos.",
      ano: 2017,
      temporada: "Verão",
      genero: ["Aventura", "Drama", "Fantasia"],
      capa: "src/design/images/made-in-abyss.jpg",
      popularidade: 77,
      curiosidade: "Apesar da aparência fofa, o anime é muito sombrio e intenso.",
    },
    {
      titulo: "Clannad",
      nota: 8.0,
      sinopse: "Tomoya conhece várias pessoas e descobre o significado da família e amizade em sua vida escolar.",
      ano: 2007,
      temporada: "Outono",
      genero: ["Drama", "Romance", "Slice of Life"],
      capa: "src/design/images/clannad.jpg",
      popularidade: 70,
      curiosidade: "Famoso por emocionar o público com sua narrativa tocante."
    },
    {
      titulo: "Erased",
      nota: 8.5,
      sinopse: "Satoru volta no tempo para impedir um assassinato e mudar o futuro.",
      ano: 2016,
      temporada: "Inverno",
      genero: ["Mistério", "Suspense", "Supernatural"],
      capa: "src/design/images/erased.jpg",
      popularidade: 85,
      curiosidade: "Baseado em um mangá premiado e muito elogiado.",
    },
    {
      titulo: "Parasyte: The Maxim",
      nota: 8.4,
      sinopse: "Um estudante é infectado por um parasita alienígena e luta para manter sua humanidade.",
      ano: 2014,
      temporada: "Outono",
      genero: ["Ação", "Terror", "Sci-Fi"],
      capa: "src/design/images/parasyte-the-maxim.jpg",
      popularidade: 83,
      curiosidade: "O anime explora questões filosóficas sobre a coexistência entre espécies."
    },
    {
      titulo: "Black Clover",
      nota: 7.9,
      sinopse: "Asta é um garoto sem poderes mágicos em um mundo onde a magia é tudo, e sonha em se tornar o Rei Mago.",
      ano: 2017,
      temporada: "Outono",
      genero: ["Ação", "Fantasia", "Aventura"],
      capa: "src/design/images/black-clover.jpg",
      popularidade: 78,
      curiosidade: "Apesar das críticas iniciais, ganhou grande popularidade pela sua evolução ao longo do tempo.",

    },
    {
      titulo: "The Rising of the Shield Hero",
      nota: 7.8,
      sinopse: "Naofumi é transportado para um mundo paralelo e precisa se defender como o herói do escudo.",
      ano: 2019,
      temporada: "Inverno",
      genero: ["Ação", "Fantasia", "Isekai"],
      capa: "src/design/images/the-rising-of-the-shield-hero.jpg",
      popularidade: 76,
      curiosidade: "O anime tem controvérsias, mas mantém uma base de fãs fiel.",
    },
    {
      titulo: "Angel Beats!",
      nota: 8.3,
      sinopse: "Um grupo de jovens luta para encontrar a paz em uma escola do pós-vida.",
      ano: 2010,
      temporada: "Primavera",
      genero: ["Drama", "Comédia", "Sobrenatural"],
      capa: "src/design/images/angel-beats.jpg",
      popularidade: 72,
      curiosidade: "É conhecido pela sua trilha sonora marcante e emocionante.",
    },
    {
      titulo: "Made in Abyss: Dawn of the Deep Soul",
      nota: 8.7,
      sinopse: "Continuação direta da série, com a equipe enfrentando perigos ainda maiores nas profundezas do Abismo.",
      ano: 2020,
      temporada: "Inverno",
      genero: ["Aventura", "Drama", "Fantasia"],
      capa: "src/design/images/made-in-abyss-dawn.jpg",
      popularidade: 70,
      curiosidade: "Filme que expande o universo e aprofunda os personagens da série original.",
    },
    {
      titulo: "Kaguya-sama: Love is War",
      nota: 8.7,
      sinopse: "Dois estudantes inteligentes tentam fazer o outro confessar primeiro seu amor.",
      ano: 2019,
      temporada: "Primavera",
      genero: ["Comédia", "Romance", "Slice of Life"],
      capa: "src/design/images/kaguya-sama.jpg",
      popularidade: 83,
      curiosidade: "Mistura comédia romântica com batalhas psicológicas cômicas.",
    },
    {
      titulo: "Vivy: Fluorite Eye's Song",
      nota: 8.6,
      sinopse: "Uma IA chamada Vivy luta para evitar uma guerra entre humanos e máquinas.",
      ano: 2021,
      temporada: "Primavera",
      genero: ["Ação", "Sci-Fi", "Drama"],
      capa: "src/design/images/vivy-fluorite.jpg",
      popularidade: 75,
      curiosidade: "Anime original muito elogiado pela animação e trilha sonora.",
    },
    {
      titulo: "Mob Psycho 100 II",
      nota: 8.8,
      sinopse: "Continuação da jornada do jovem esper com poderes psíquicos tentando viver normalmente.",
      ano: 2019,
      temporada: "Verão",
      genero: ["Ação", "Comédia", "Sobrenatural"],
      capa: "src/design/images/mob-pyscho-100-II.jpg",
      popularidade: 79,
      curiosidade: "Ainda melhor animado e com desenvolvimento emocional mais profundo.",
    },
    {
      titulo: "Mob Psycho 100 III",
      nota: 8.8,
      sinopse: "Continuação da jornada do jovem esper com poderes psíquicos tentando viver normalmente.",
      ano: 2019,
      temporada: "Outono",
      genero: ["Ação", "Comédia", "Sobrenatural"],
      capa: "src/design/images/mob-pyscho-100-III.jpg",
      popularidade: 79,
      curiosidade: "Mob Psycho 100 foi criado pelo mangaká ONE, que também é responsável pelo sucesso One Punch Man."
    },
    {
      titulo: "To Your Eternity",
      nota: 8.7,
      sinopse: "Uma entidade imortal viaja pelo mundo descobrindo o significado da vida e humanidade.",
      ano: 2021,
      temporada: "Primavera",
      genero: ["Drama", "Fantasia", "Aventura"],
      capa: "src/design/images/to-your-eternity.jpg",
      popularidade: 78,
      curiosidade: "Emocionante e reflexivo, ganhou elogios por sua narrativa profunda."
    },
    {
        titulo: "Ergo Proxy",
        nota: 8.0,
        sinopse: "Em um mundo pós-apocalíptico, uma investigadora descobre segredos obscuros envolvendo seres chamados Proxy.",
        ano: 2006,
        temporada: "Inverno",
        genero: ["Sci-Fi", "Mistério", "Psicológico"],
        capa: "src/design/images/ergo-proxy.jpg",
        popularidade: 65,
        curiosidade: "Mistura elementos de filosofia, ficção científica e suspense."
      },
      {
        titulo: "The Promised Neverland",
        nota: 8.6,
        sinopse: "Crianças descobrem um terrível segredo sobre o orfanato onde vivem e planejam escapar.",
        ano: 2019,
        temporada: "Inverno",
        genero: ["Mistério", "Suspense", "Terror"],
        popularidade: 90,
        curiosidade: "A música de abertura de The Promised Neverland, Touch Off da banda UVERworld, foi escrita especialmente para refletir a rebeldia das crianças contra seu destino.",
        capa: "src/design/images/the-promised-neverland.jpg"
      },
      {
        titulo: "Yuri on Ice",
        nota: 8.2,
        sinopse: "A história de um patinador artístico buscando redenção e seu relacionamento com o treinador.",
        ano: 2016,
        temporada: "Outono",
        genero: ["Esporte", "Drama", "Romance"],
        capa: "src/design/images/yuri-on-ice.jpg",
        popularidade: 68,
        curiosidade: "Foi o primeiro anime de esporte com temática LGBTQ+ a ganhar grande popularidade.",
      },
      {
        titulo: "Bakuman",
        nota: 8.2,
        sinopse: "Dois jovens sonham em se tornar mangakás famosos e mostram os desafios da indústria de mangá.",
        ano: 2010,
        temporada: "Outono",
        genero: ["Comédia", "Drama", "Slice of Life"],
        capa: "src/design/images/bakuman.jpg",
        popularidade: 60,
        curiosidade: "Criado pelo mesmo autor de Death Note, Tsugumi Ohba."
      },
      {
        titulo: "No Game No Life",
        nota: 8.0,
        sinopse: "Irmãos gênio são transportados para um mundo onde tudo é decidido por jogos.",
        ano: 2014,
        temporada: "Primavera",
        genero: ["Fantasia", "Comédia", "Aventura"],
        capa: "src/design/images/no-game-no-life.jpg",
        popularidade: 75,
        curiosidade: "Famoso por sua arte colorida e jogos estratégicos complexos."
      },
      {
        titulo: "The Ancient Magus' Bride",
        nota: 8.0,
        sinopse: "Uma jovem órfã é comprada por um mago misterioso e entra num mundo de magia e mistério.",
        ano: 2017,
        temporada: "Outono",
        genero: ["Fantasia", "Drama", "Romance"],
        capa: "src/design/images/the-ancient-magus.jpg",
        popularidade: 70,
        curiosidade: "Popular pela sua atmosfera sombria e personagens cativantes."
      },
      {
        titulo: "Anohana: The Flower We Saw That Day",
        nota: 8.4,
        sinopse: "Um grupo de amigos tenta superar a perda de uma amiga de infância e resolver sentimentos não ditos.",
        ano: 2011,
        temporada: "Primavera",
        genero: ["Drama", "Slice of Life", "Sobrenatural"],
        capa: "src/design/images/anohana-the-flower.jpg",
        popularidade: 65,
        curiosidade: "É famoso por emocionar profundamente o público."
      },
      {
        titulo: "Hellsing Ultimate",
        nota: 8.3,
        sinopse: "Organização Hellsing combate vampiros e criaturas sobrenaturais para proteger a Inglaterra.",
        ano: 2006,
        temporada: "Outono",
        genero: ["Ação", "Terror", "Sobrenatural"],
        capa: "src/design/images/hellsing-ultimate.jpg",
        popularidade: 60,
        curiosidade: "Reconhecido pela animação intensa e sangue exagerado."
      },
      {
        titulo: "Beastars",
        nota: 8.0,
        sinopse: "Em um mundo de animais antropomórficos, um lobo luta com seus instintos e sentimentos.",
        ano: 2019,
        temporada: "Outono",
        genero: ["Drama", "Romance", "Slice of Life"],
        capa: "src/design/images/beastarts.jpg",
        popularidade: 68,
        curiosidade: "Destaca-se pela abordagem adulta e psicológica dos personagens.",
      },
      {
        titulo: "Land of the Lustrous",
        nota: 8.3,
        sinopse: "Seres de cristal lutam para sobreviver em um mundo pós-apocalíptico e descobrir sua origem.",
        ano: 2017,
        temporada: "Outono",
        genero: ["Ação", "Drama", "Fantasia"],
        capa: "src/design/images/land-of-the-lustrous.jpg",
        popularidade: 63,
        curiosidade: "Animação em CGI com estilo único e elogiado."
      },
      {
        titulo: "Terror in Resonance",
        nota: 8.2,
        sinopse: "Dois jovens terroristas misteriosos desafiam a polícia em uma Tóquio cheia de segredos.",
        ano: 2014,
        temporada: "Verão",
        genero: ["Mistério", "Suspense", "Drama"],
        capa: "src/design/images/terror-in-resonance.jpg",
        popularidade: 60,
        curiosidade: "Dirigido pelo criador de Death Note, trazendo suspense intenso."
      },
      {
        titulo: "Blue Exorcist",
        nota: 7.7,
        sinopse: "Um jovem descobre ser filho de Satanás e decide se tornar um exorcista para lutar contra o mal.",
        ano: 2011,
        temporada: "Primavera",
        genero: ["Ação", "Fantasia", "Sobrenatural"],
        capa: "src/design/images/blue-exorcist.jpg",
        popularidade: 75,
        curiosidade: "Possui uma base de fãs sólida e uma segunda temporada lançada anos depois."
      },
      {
        titulo: "Noragami",
        nota: 7.9,
        sinopse: "Um deus menor luta para ganhar seguidores enquanto ajuda humanos e enfrenta ameaças sobrenaturais.",
        ano: 2014,
        temporada: "Inverno",
        genero: ["Ação", "Comédia", "Sobrenatural"],
        capa: "src/design/images/noragami.jpg",
        popularidade: 70,
        curiosidade: "Mistura comédia e ação sobrenatural de forma leve e divertida."
      },
      {
        titulo: "Mushishi",
        nota: 8.5,
        sinopse: "Ginko, um 'Mushi-shi', investiga seres primordiais chamados mushi em uma jornada calma e filosófica.",
        ano: 2005,
        temporada: "Outono",
        genero: ["Fantasia", "Mistério", "Slice of Life"],
        capa: "src/design/images/mushishi.jpg",
        popularidade: 65,
        curiosidade: "Conhecido pelo ritmo tranquilo e atmosfera contemplativa."
      },
        {
          titulo: "Chainsaw Man",
          nota: 8.5,
          sinopse: "Denji, um jovem endividado, faz um pacto com o demônio Pochita, tornando-se o híbrido Chainsaw Man e se junta à agência caçadora de demônios.",
          ano: 2022,
          temporada: "Outono",
          genero: ["Ação", "Sobrenatural", "Thriller"],
          capa: "src/design/images/chainsaw-man.jpg",
          popularidade: 91,
          curiosidade: "A música de abertura “KICK BACK” ultrapassou 100 milhões de visualizações em seis meses."
        },
        {
          titulo: "Kaiju No. 8",
          nota: 7.8,
          sinopse: "Kafka Hibino, um homem que limpa restos de kaijus, adquire poderes de monstro e luta para se juntar à força de defesa e proteger a humanidade.",
          ano: 2024,
          temporada: "Outono",
          genero: ["Ação", "Ciência-Ficção", "Shonen"],
          capa: "src/design/images/kaiju-8.jpg",
          popularidade: 85,
          curiosidade: "Terá um filme compilatório com episódio inédito lançado em março de 2025."
        },
        {
          titulo: "DanDaDan",
          nota: 8.7,
          sinopse: "Momo e Okarun, ao explorarem o sobrenatural (yōkai e alienígenas), descobrem poderes surpreendentes enquanto enfrentam perigos juntos.",
          ano: 2024,
          temporada: "Outono",
          genero: ["Ação", "Fantasia", "Sobrenatural"],
          capa: "src/design/images/dan-da-dan.jpg",
          popularidade: 88,
          curiosidade: "DanDaDan mistura elementos de terror, comédia e ficção científica, criando uma trama única e imprevisível. A série ganhou destaque por seu ritmo acelerado e personagens carismáticos."
        },
        {
          titulo: "Frieren: Beyond Journey’s End",
          nota: 9.3,
          sinopse: "Após derrotar o Rei Demônio, Frieren, uma elfa maga, reflete sobre seus anos de aventura e decide guiar um jovem aprendiz em uma jornada de redescoberta.",
          ano: 2023,
          temporada: "Outono",
          genero: ["Fantasia", "Aventura", "Drama"],
          capa: "src/design/images/frieren-beyond.jpg",
          popularidade: 92,
          curiosidade: " O anime usa uma narrativa fragmentada que exige que o espectador junte as peças da história. Isso torna a experiência mais envolvente e cheia de mistérios."
        },
        {
          titulo: "The Apothecary Diaries",
          nota: 8.9,
          sinopse: "Maomao, uma serva obcecada por remédios e venenos no palácio imperial, resolve mistérios usando seu conhecimento médico e dedução.",
          ano: 2023,
          temporada: "Outono",
          genero: ["Mistério", "Drama", "Romance"],
          capa: "src/design/images/the-apothecary-diaries.jpg",
          popularidade: 87,
          curiosidade: "A protagonista Maomao é inspirada em mulheres sábias da medicina tradicional chinesa, e muitas das doenças e remédios retratados no anime têm base real em práticas medicinais da Ásia oriental."
        },
        {
          titulo: "Wind Breaker",
          nota: 7.5,
          sinopse: "Haruka Sakura se muda para a escola de delinquentes e logo descobre um grupo que protege a cidade e decide se tornar o melhor deles.",
          ano: 2024,
          temporada: "Primavera",
          genero: ["Ação", "Esportes", "Shonen"],
          capa: "src/design/images/wind-breaker.jpg",
          popularidade: 80,
          curiosidade: " O protagonista Haruka Sakura começa como um anti-herói solitário e violento, e a história mostra seu crescimento ao aprender o valor dos laços com os outros."
        },
        {
          titulo: "Sakamoto Days",
          nota: 8.6,
          sinopse: "Taro Sakamoto, ex-assassino lendário, agora vive como dono de conveniência e deve usar suas habilidades para proteger a família quando seu passado retorna.",
          ano: 2025,
          temporada: "Inverno",
          genero: ["Ação", "Comédia", "Drama"],
          capa: "src/design/images/sakamoto-days.jpg",
          popularidade: 84,
          curiosidade: "akamoto Days foi inspirado em filmes de ação e comédia como “John Wick” e “Mr. & Mrs. Smith”. O autor, Yuto Suzuki, equilibra humor cotidiano com cenas de luta coreografadas de forma cinematográfica."
        },
        {
          titulo: "Fire Force",
          nota: 8.0,
          sinopse: "Shinra e a Companhia 8 enfrentam combustões humanas misteriosas em Tóquio enquanto segredos sombrios são revelados em batalhas intensas.",
          ano: 2025,
          temporada: "Primavera",
          genero: ["Ação", "Sobrenatural", "Fantasia"],
          capa: "src/design/images/fire-force.jpg",
          popularidade: 83,
          curiosidade: "A épica luta Shinra vs Burns (ep.6) foi considerada das melhores de 2025."
        },
        {
          titulo: "Lazarus",
          nota: 7.4,
          sinopse: "(Info limitada) Nova série de sci‑fi/steampunk, ainda aguardada com expectativa por ter sinopse futurista e visual de impacto.",
          ano: 2025,
          temporada: "Verão",
          genero: ["Sci-fi", "Steampunk", "Aventura"],
          capa: "src/design/images/lazarus.jpg",
          popularidade: 76,
          curiosidade: "Criado por Shinichirō Watanabe, promete visual e narrativa marcantes."
        },
        {
          titulo: "Spy × Family",
          nota: 8.8,
          sinopse: "A família Forger continua as missões Loid e Yor disfarçados, e Anya na escola, entre espionagem, comédia e momentos familiares tensos.",
          ano: 2025,
          temporada: "Primavera",
          genero: ["Ação", "Comédia", "Slice of Life", "Espionagem"],
          capa:"src/design/images/spy-family.jpg",
          popularidade: 90,
          curiosidade: "Indicada como ‘Melhor Série Contínua’ e vencedora de ‘Melhor Comédia’ nos Crunchyroll Awards."
        },
          {
            titulo: "Lycoris Recoil: Friends Are Thieves of Time",
            nota: 8.2,
            sinopse: "Segue um spin-off leve de ‘Lycoris Recoil’, com foco em missões urbanas divertidas protagonizadas por mulheres agentes.",
            ano: 2025,
            temporada: "Primavera",
            genero: ["Ação", "Slice of Life", "Comédia"],
            capa: "src/design/images/lycoris-recoil.jpg",
            popularidade: 78,
            curiosidade: "Continuação do sucesso de 2022, mantendo o tom descontraído e de ação leve." 
          },
          {
            titulo: "Mono",
            nota: 7.9,
            sinopse: "Animação experimental que celebra a vida cotidiana através de visuais artísticos e momentos contemplativos.",
            ano: 2025,
            temporada: "Outono",
            genero: ["Slice of Life", "Artes", "Drama"],
            capa: "src/design/images/mono.jpg",
            popularidade: 65,
            curiosidade: "Destacado pelo site Vulture como 'celebração artística' em 2025" ,
          },
          {
            titulo: "Moonrise",
            nota: 7.6,
            sinopse: "Original da WIT Studio, sci‑fi com exploração espacial, drama e visuais marcantes.",
            ano: 2025,
            temporada: "Verão",
            genero: ["Sci‑fi", "Mistério", "Aventura"],
            capa: "src/design/images/moonrise.jpg",
            popularidade: 74,
            curiosidade: "Citado entre os lançamentos mais aguardados de inverno/verão 2025" ,
            }, 
            {
              titulo: "Devil May Cry",
              nota: 8.1,
              sinopse: "Baseado no jogo, segue Dante em batalhas brutais contra demônios no inferno e na Terra.",
              ano: 2025,
              temporada: "Primavera",
              genero: ["Ação", "Sobrenatural", "Dark Fantasy"],
              capa: "src/design/images/devil-may-cry.jpg",
              popularidade: 82,
              curiosidade: "Anime exclusivo da Netflix, produzido com grande investimento em animação pesada."
            },
            {
              titulo: "Bleach: Thousand-Year Blood War – Final Part",
              nota: 8.9,
              sinopse: "Confronto final entre Ichigo e Yhwach no último arco épico da franquia.",
              ano: 2025,
              temporada: "Verão",
              genero: ["Ação", "Fantasia", "Shonen"],
              capa: "src/design/images/bleach-thousand-year.jpg",
              popularidade: 93,
              curiosidade: "Parte final do arco mais aclamado da franquia, encerrando a saga do Sangue Milenar." 
            },
            {
              titulo: "Ousama Ranking",
              nota: 8.7,
              sinopse: "Bojji, um jovem príncipe surdo e frágil, luta para se tornar um grande rei em um mundo que o subestima.",
              ano: 2021,
              temporada: "Outono",
              genero: ["Fantasia", "Aventura", "Drama"],
              capa: "src/design/images/ousama-ranking.jpg",
              popularidade: 87,
              curiosidade: "Apesar da aparência infantil, o anime trata de temas maduros e emocionais."
            }                   
];